name: cbuild

on: [push]

permissions:
  contents: read

jobs:
  cbuild:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Build the project
        run: |
          make