name: ctest

on: [push]

permissions:
  contents: read

jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Test the project
        run: |
          make test